### PR TITLE
feature: Add ability to change authorization servers

### PR DESCRIPTION
**Pull request by fpunny**
Hey @antoinejaussoin,

Thanks for your work on this package. I have gotten to use it in one of my projects but found that it was lacking in the ability to change authorization servers. Hence, I made this PR in hopes of adding this functionality for everyone (and myself) to use!

I hope it's of quality and thanks for your time,
Fred

### CODE REVIEW

**Comment by antoinejaussoin** [comment]
Hi Fred, thank you so much for your PR! 

One issue though: it doesn't pass the linting tests (you might need to install prettier, or check the test results above). If you have an issue with this, perhaps we could merge to a separate branch (not main) so I can fix it myself. WDYT?

As soon as it's merged, I will push to NPM.

**Comment by antoinejaussoin** [comment]
Nevermind actually, will merge to a temp branch and fix it

**Comment by antoinejaussoin** [comment]
@fpunny : all merged, and published to NPM under version 1.1.0. Thanks again!

**Comment by fpunny** [comment]
@antoinejaussoin Whoops, just saw this and my bad for missing the linting tests. But once again, thanks for putting time into making this update! :D

**Pull request merged**
